<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1alpha\ServerReflectionResponse;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MessageResponseFileDescriptorResponse implements \Grpc\Reflection\V1alpha\ServerReflectionResponse\MessageResponse
{
    /**
     * @param ?\Grpc\Reflection\V1alpha\FileDescriptorResponse $fileDescriptorResponse This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     */
    public function __construct(
        #[Reflection\Field(4, new Reflection\ObjectT(\Grpc\Reflection\V1alpha\FileDescriptorResponse::class))]
        public ?\Grpc\Reflection\V1alpha\FileDescriptorResponse $fileDescriptorResponse = null,
    ) {}
}
