<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1alpha\ServerReflectionResponse;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MessageResponseAllExtensionNumbersResponse implements \Grpc\Reflection\V1alpha\ServerReflectionResponse\MessageResponse
{
    /**
     * @param ?\Grpc\Reflection\V1alpha\ExtensionNumberResponse $allExtensionNumbersResponse This message is used to answer all_extension_numbers_of_type request.
     */
    public function __construct(
        #[Reflection\Field(5, new Reflection\ObjectT(\Grpc\Reflection\V1alpha\ExtensionNumberResponse::class))]
        public ?\Grpc\Reflection\V1alpha\ExtensionNumberResponse $allExtensionNumbersResponse = null,
    ) {}
}
