<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1alpha\ServerReflectionResponse;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MessageResponseListServicesResponse implements \Grpc\Reflection\V1alpha\ServerReflectionResponse\MessageResponse
{
    /**
     * @param ?\Grpc\Reflection\V1alpha\ListServiceResponse $listServicesResponse This message is used to answer list_services request.
     */
    public function __construct(
        #[Reflection\Field(6, new Reflection\ObjectT(\Grpc\Reflection\V1alpha\ListServiceResponse::class))]
        public ?\Grpc\Reflection\V1alpha\ListServiceResponse $listServicesResponse = null,
    ) {}
}
