<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Thesis\Grpc\Reflection\V1alpha\ServerReflectionResponse;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MessageResponseErrorResponse implements \Thesis\Grpc\Reflection\V1alpha\ServerReflectionResponse\MessageResponse
{
    /**
     * @param ?\Thesis\Grpc\Reflection\V1alpha\ErrorResponse $errorResponse This message is used when an error occurs.
     */
    public function __construct(
        #[Reflection\Field(7, new Reflection\ObjectT(\Thesis\Grpc\Reflection\V1alpha\ErrorResponse::class))]
        public ?\Thesis\Grpc\Reflection\V1alpha\ErrorResponse $errorResponse = null,
    ) {}
}
