<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1alpha;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * The type name and extension number sent by the client when requesting
 * file_containing_extension.
 */
final readonly class ExtensionRequest
{
    /**
     * @param string $containingType Fully-qualified type name. The format should be <package>.<type>
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $containingType = '',
        #[Reflection\Field(2, Reflection\Int32T::T)]
        public int $extensionNumber = 0,
    ) {}
}
