<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1alpha;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * A list of extension numbers sent by the server answering
 * all_extension_numbers_of_type request.
 */
final readonly class ExtensionNumberResponse
{
    /**
     * @param string $baseTypeName Full name of the base type, including the package name. The format
     * is <package>.<type>
     * @param list<int> $extensionNumber
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $baseTypeName = '',
        #[Reflection\Field(2, new Reflection\ListT(Reflection\Int32T::T))]
        public array $extensionNumber = [],
    ) {}
}
