<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1alpha;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * A list of ServiceResponse sent by the server answering list_services request.
 */
final readonly class ListServiceResponse
{
    /**
     * @param list<\Grpc\Reflection\V1alpha\ServiceResponse> $service The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(new Reflection\ObjectT(\Grpc\Reflection\V1alpha\ServiceResponse::class)))]
        public array $service = [],
    ) {}
}
