<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1alpha;

use Override;
use Thesis\Grpc;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class ServerReflectionServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \Grpc\Reflection\V1alpha\ServerReflectionServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('grpc.reflection.v1alpha.ServerReflection', [
            new Server\Rpc(
                handle: new Server\Handle('ServerReflectionInfo', \Grpc\Reflection\V1alpha\ServerReflectionRequest::class),
                handler: new Server\BidirectionalStreamHandler($this->server->serverReflectionInfo(...)),
                type: Grpc\RpcType::BidirectionalStream,
            ),
        ]);
    }
}
