<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1alpha;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * The message sent by the client when calling ServerReflectionInfo method.
 */
final readonly class ServerReflectionRequest
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $host = '',
        #[Reflection\OneOf([
            \Grpc\Reflection\V1alpha\ServerReflectionRequest\MessageRequestFileByFilename::class,
            \Grpc\Reflection\V1alpha\ServerReflectionRequest\MessageRequestFileContainingSymbol::class,
            \Grpc\Reflection\V1alpha\ServerReflectionRequest\MessageRequestFileContainingExtension::class,
            \Grpc\Reflection\V1alpha\ServerReflectionRequest\MessageRequestAllExtensionNumbersOfType::class,
            \Grpc\Reflection\V1alpha\ServerReflectionRequest\MessageRequestListServices::class,
        ])]
        public ?\Grpc\Reflection\V1alpha\ServerReflectionRequest\MessageRequest $messageRequest = null,
    ) {}
}
