<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.20
 *   protoc               — v6.33.5
 * Source: tests/protos/echo_v1.proto
 */

declare(strict_types=1);

namespace Echos\Api\V1;

use Override;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class EchoServiceServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \Echos\Api\V1\EchoServiceServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('echos.api.v1.EchoService', [
            new Server\Rpc(
                new Server\Handle('Echo', \Echos\Api\V1\EchoRequest::class),
                new Server\UnaryHandler($this->server->echo(...)),
                Server\RpcType::Unary,
            ),
        ]);
    }
}
