<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: tests/protos/echo_v1.proto
 */

declare(strict_types=1);

namespace Echos\Api\V1;

use Amp\Cancellation;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
interface EchoServiceServer
{
    public function echo(
        \Echos\Api\V1\EchoRequest $request,
        Metadata $md,
        Cancellation $cancellation,
    ): \Echos\Api\V1\EchoResponse;
}
