<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.20
 *   protoc               — v6.33.5
 * Source: tests/protos/echo_v1.proto
 */

declare(strict_types=1);

namespace Echos\Api\V1;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class EchoServiceClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function echo(
        \Echos\Api\V1\EchoRequest $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Echos\Api\V1\EchoResponse {
        /** @var Client\Invoke<\Echos\Api\V1\EchoRequest, \Echos\Api\V1\EchoResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/echos.api.v1.EchoService/Echo',
            type: \Echos\Api\V1\EchoResponse::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
