<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: tests/protos/echo_v1.proto
 */

declare(strict_types=1);

namespace Echos\Api\V1;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class TestsProtosEchoV1DescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Chp0ZXN0cy9wcm90b3MvZWNob192MS5wcm90bxIMZWNob3MuYXBpLnYxIikKC0VjaG9SZXF1ZXN0EhoKCHNlbnRlbmNlGAEgASgJUghzZW50ZW5jZSIqCgxFY2hvUmVzcG9uc2USGgoIc2VudGVuY2UYASABKAlSCHNlbnRlbmNlMkwKC0VjaG9TZXJ2aWNlEj0KBEVjaG8SGS5lY2hvcy5hcGkudjEuRWNob1JlcXVlc3QaGi5lY2hvcy5hcGkudjEuRWNob1Jlc3BvbnNlSokCCgYSBAAADgEKCAoBDBIDAAASCggKAQISAwIAFQoKCgIEABIEBAAGAQoKCgMEAAESAwQIEwoLCgQEAAIAEgMFBBgKDAoFBAACAAUSAwUECgoMCgUEAAIAARIDBQsTCgwKBQQAAgADEgMFFhcKCgoCBAESBAgACgEKCgoDBAEBEgMICBQKCwoEBAECABIDCQQYCgwKBQQBAgAFEgMJBAoKDAoFBAECAAESAwkLEwoMCgUEAQIAAxIDCRYXCgoKAgYAEgQMAA4BCgoKAwYAARIDDAgTCgsKBAYAAgASAw0EMQoMCgUGAAIAARIDDQgMCgwKBQYAAgACEgMNDRgKDAoFBgACAAMSAw0jL2IGcHJvdG8z';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'tests/protos/echo_v1.proto',
            messages: [
                new File\MessageDescriptor('echos.api.v1.EchoRequest', \Echos\Api\V1\EchoRequest::class),
                new File\MessageDescriptor('echos.api.v1.EchoResponse', \Echos\Api\V1\EchoResponse::class),
            ],
            services: [
                new File\ServiceDescriptor(
                    name: 'echos.api.v1.EchoService',
                    methods: [
                        new File\MethodDescriptor('Echo', false, false),
                    ],
                ),
            ],
        ));
    }
}
