<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1alpha\ServerReflectionRequest;

/**
 * @api
 * @phpstan-sealed (
 *   MessageRequestFileByFilename |
 *   MessageRequestFileContainingSymbol |
 *   MessageRequestFileContainingExtension |
 *   MessageRequestAllExtensionNumbersOfType |
 *   MessageRequestListServices
 * )
 */
interface MessageRequest {}
