<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1alpha\ServerReflectionRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MessageRequestFileContainingExtension implements \Grpc\Reflection\V1alpha\ServerReflectionRequest\MessageRequest
{
    /**
     * @param ?\Grpc\Reflection\V1alpha\ExtensionRequest $fileContainingExtension Find the proto file which defines an extension extending the given
     * message type with the given field number.
     */
    public function __construct(
        #[Reflection\Field(5, new Reflection\ObjectT(\Grpc\Reflection\V1alpha\ExtensionRequest::class))]
        public ?\Grpc\Reflection\V1alpha\ExtensionRequest $fileContainingExtension = null,
    ) {}
}
