<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1alpha\ServerReflectionRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MessageRequestFileByFilename implements \Grpc\Reflection\V1alpha\ServerReflectionRequest\MessageRequest
{
    /**
     * @param string $fileByFilename Find a proto file by the file name.
     */
    public function __construct(
        #[Reflection\Field(3, Reflection\StringT::T)]
        public string $fileByFilename = '',
    ) {}
}
