<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1/reflection.proto
 */

declare(strict_types=1);

namespace Thesis\Grpc\Reflection\V1;

use Amp\Cancellation;
use Thesis\Grpc\Metadata;
use Thesis\Grpc\Server;

/**
 * @api
 */
interface ServerReflectionServer
{
    /**
     * The reflection service is structured as a bidirectional stream, ensuring
     * all related requests go to a single server.
     *
     * @param Server\BidirectionalStreamChannel<\Thesis\Grpc\Reflection\V1\ServerReflectionRequest, \Thesis\Grpc\Reflection\V1\ServerReflectionResponse> $stream
     */
    public function serverReflectionInfo(
        Server\BidirectionalStreamChannel $stream,
        Metadata $md,
        Cancellation $cancellation,
    ): void;
}
