<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * The error code and error message sent by the server when an error occurs.
 */
final readonly class ErrorResponse
{
    /**
     * @param int $errorCode This field uses the error codes defined in grpc::StatusCode.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public int $errorCode = 0,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $errorMessage = '',
    ) {}
}
