<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Serialized FileDescriptorProto messages sent by the server answering
 * a file_by_filename, file_containing_symbol, or file_containing_extension
 * request.
 */
final readonly class FileDescriptorResponse
{
    /**
     * @param list<string> $fileDescriptorProto Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(Reflection\BytesT::T))]
        public array $fileDescriptorProto = [],
    ) {}
}
