<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1;

use Override;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class ServerReflectionServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \Grpc\Reflection\V1\ServerReflectionServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('grpc.reflection.v1.ServerReflection', [
            new Server\Rpc(
                new Server\Handle('ServerReflectionInfo', \Grpc\Reflection\V1\ServerReflectionRequest::class),
                new Server\BidirectionalStreamHandler($this->server->serverReflectionInfo(...)),
                Server\RpcType::BidirectionalStream,
            ),
        ]);
    }
}
