<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc;
use Thesis\Grpc\Client;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class ServerReflectionClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * The reflection service is structured as a bidirectional stream, ensuring
     * all related requests go to a single server.
     *
     * @return Client\BidirectionalStreamChannel<\Grpc\Reflection\V1\ServerReflectionRequest, \Grpc\Reflection\V1\ServerReflectionResponse>
     */
    public function serverReflectionInfo(
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): Client\BidirectionalStreamChannel {
        /** @var Client\Invoke<\Grpc\Reflection\V1\ServerReflectionRequest, \Grpc\Reflection\V1\ServerReflectionResponse> $invoke */
        $invoke = new Client\Invoke(
            method: '/grpc.reflection.v1.ServerReflection/ServerReflectionInfo',
            output: \Grpc\Reflection\V1\ServerReflectionResponse::class,
            type: Grpc\RpcType::BidirectionalStream,
        );

        $stream = $this->client->createStream(
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );

        return new Client\BidirectionalStreamChannel($stream);
    }
}
