<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1\ServerReflectionRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MessageRequestAllExtensionNumbersOfType implements \Grpc\Reflection\V1\ServerReflectionRequest\MessageRequest
{
    /**
     * @param string $allExtensionNumbersOfType Finds the tag numbers used by all known extensions of the given message
     * type, and appends them to ExtensionNumberResponse in an undefined order.
     * Its corresponding method is best-effort: it's not guaranteed that the
     * reflection service will implement this method, and it's not guaranteed
     * that this method will provide all extensions. Returns
     * StatusCode::UNIMPLEMENTED if it's not implemented.
     * This field should be a fully-qualified type name. The format is
     * <package>.<type>
     */
    public function __construct(
        #[Reflection\Field(6, Reflection\StringT::T)]
        public string $allExtensionNumbersOfType = '',
    ) {}
}
