<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.4.2
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1\ServerReflectionRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MessageRequestFileContainingSymbol implements \Grpc\Reflection\V1\ServerReflectionRequest\MessageRequest
{
    /**
     * @param string $fileContainingSymbol Find the proto file that declares the given fully-qualified symbol name.
     * This field should be a fully-qualified symbol name
     * (e.g. <package>.<service>[.<method>] or <package>.<type>).
     */
    public function __construct(
        #[Reflection\Field(4, Reflection\StringT::T)]
        public string $fileContainingSymbol = '',
    ) {}
}
