<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1/reflection.proto
 */

declare(strict_types=1);

namespace Grpc\Reflection\V1\ServerReflectionRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MessageRequestListServices implements \Grpc\Reflection\V1\ServerReflectionRequest\MessageRequest
{
    /**
     * @param string $listServices List the full names of registered services. The content will not be
     * checked.
     */
    public function __construct(
        #[Reflection\Field(7, Reflection\StringT::T)]
        public string $listServices = '',
    ) {}
}
