<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.19
 *   protoc               — v6.33.5
 */

declare(strict_types=1);

\Thesis\Protobuf\Registry\Pool::get()->register(
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Grpc\Reflection\V1\GrpcReflectionV1ReflectionDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Grpc\Reflection\V1alpha\GrpcReflectionV1alphaReflectionDescriptorRegistry()),
);
