<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1alpha/reflection.proto
 */

declare(strict_types=1);

namespace Thesis\Grpc\Reflection\V1alpha;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * The message sent by the server to answer ServerReflectionInfo method.
 */
final readonly class ServerReflectionResponse
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $validHost = '',
        #[Reflection\Field(2, new Reflection\ObjectT(\Thesis\Grpc\Reflection\V1alpha\ServerReflectionRequest::class))]
        public ?\Thesis\Grpc\Reflection\V1alpha\ServerReflectionRequest $originalRequest = null,
        #[Reflection\OneOf([
            \Thesis\Grpc\Reflection\V1alpha\ServerReflectionResponse\MessageResponseFileDescriptorResponse::class,
            \Thesis\Grpc\Reflection\V1alpha\ServerReflectionResponse\MessageResponseAllExtensionNumbersResponse::class,
            \Thesis\Grpc\Reflection\V1alpha\ServerReflectionResponse\MessageResponseListServicesResponse::class,
            \Thesis\Grpc\Reflection\V1alpha\ServerReflectionResponse\MessageResponseErrorResponse::class,
        ])]
        public ?\Thesis\Grpc\Reflection\V1alpha\ServerReflectionResponse\MessageResponse $messageResponse = null,
    ) {}
}
