<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.6.1
 *   protoc               — v6.33.5
 * Source: grpc/reflection/v1/reflection.proto
 */

declare(strict_types=1);

namespace Thesis\Grpc\Reflection\V1\ServerReflectionRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MessageRequestFileContainingExtension implements \Thesis\Grpc\Reflection\V1\ServerReflectionRequest\MessageRequest
{
    /**
     * @param ?\Thesis\Grpc\Reflection\V1\ExtensionRequest $fileContainingExtension Find the proto file which defines an extension extending the given
     * message type with the given field number.
     */
    public function __construct(
        #[Reflection\Field(5, new Reflection\ObjectT(\Thesis\Grpc\Reflection\V1\ExtensionRequest::class))]
        public ?\Thesis\Grpc\Reflection\V1\ExtensionRequest $fileContainingExtension = null,
    ) {}
}
